language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: "mannix.hacku.aws"
  region: us-west-2
